tweakwcs/matchutils.py
Fix a bug in the `match` which happened due to a copy/paste typo resulting in `refcat` being used instead of `imcat`.
=> Fix a bug in the match - use of refcat instead of imcat

tweakwcs/imalign.py, tweakwcs/linearfit.py, tweakwcs/wcsimage.py
See: https://github.com/spacetelescope/jwst/pull/2796 and https://github.com/spacetelescope/jwst/pull/2797.
=> Port recent bug fixes from JWST pipeline

tweakwcs/imalign.py
This PR implements temporary work around  issues described in https://github.com/spacetelescope/tweakwcs/issues/12#issuecomment-441960867 This PR should allow running `tweak_image_wcs()` on `NDData` objects with FITS WCS.
CC: @stsci-hack
=> Workaround for issues to allow tweak_image_wcs() to work with FITS WCS

notebooks/align_fits_wcs.ipynb
This PR adds a simple example of using the convenience function `tweak_image_wcs()` to align two images that use `FITS WCS`. This approach does not allow much customization. Another example will be added later.
CC: @stsci-hack @stscicrawford
=> Add notebook example of using quick convenience functions

tweakwcs/imalign.py, tweakwcs/wcsimage.py
=> Add fit RMS to tweakwcs info in meta

CHANGELOG.rst
Simply forgot to update changelog before the last release.
=> Add release info to the changelog

tweakwcs/wcsimage.py
This PR ports reliability enhancements from https://github.com/spacetelescope/jwst/pull/2939 to this repository.
=> Make code more reliable when all catalogs in a group are empty

CHANGELOG.rst, tweakwcs/linearfit.py
Finish unfinished stuff from #50.
=> Fix undefined weights when performing un-weighted fits

CHANGELOG.rst, tweakwcs/wcsimage.py
This PR should fix the undefined RA bug reported in #55. Somehow the indentation got messed up and  the code that was supposed to be under the `else` branch got outside it...
=> Fix undefined RA variable for small (1-2 sources) catalogs

src/carrutils.c
Touch up missed stuff from #63
=> C code cleanup: consistent indentation

setup.py
* numpy - C code remove
* setuptools.Extension - C code removed
(No immediate release required.)
=> setup.py: Remove imports

README.rst
Displays the build status of the `master` branch
=> Add azure badge to README.rst

tweakwcs/tests/test_nop.py, tweakwcs/tests/test_wcsutils.py
=> Add wcsutils tests

tweakwcs/linalg.py, tweakwcs/linearfit.py, tweakwcs/tests/test_linalg.py, tweakwcs/tests/test_linearfit.py
Add unit tests for `linalg` and `linearfit` modules.
=> Add unit tests for linalg and linearfit

tweakwcs/tests/test_linearfit.py
The additional test(s) is designed to check that weighting "works" by checking that bad data are being ignored.
=> Additional linearfit.py unit tests

.coveragerc, .gitignore, azure-templates.yml
=> Azure codecov2

README.rst
=> Add codecov badge

CHANGELOG.rst, tweakwcs/__init__.py, tweakwcs/imalign.py, tweakwcs/linalg.py, tweakwcs/linearfit.py, tweakwcs/matchutils.py, tweakwcs/tests/helper_tpwcs.py, tweakwcs/tests/test_jwst_utils.py, tweakwcs/tests/test_matchutils.py, tweakwcs/tests/test_tpwcs.py, tweakwcs/utils/jwst_utils.py
Additional tests that cover `tpwcs` and `utils/jwst_utils`
=> Add unit tests for TPWCS and derived classes and related modules

tweakwcs/imalign.py, tweakwcs/linalg.py, tweakwcs/matchutils.py, tweakwcs/tests/helper_tpwcs.py, tweakwcs/tpwcs.py, tweakwcs/wcsimage.py
=> Code cleanup

tweakwcs/linalg.py, tweakwcs/linearfit.py, tweakwcs/matchutils.py, tweakwcs/tests/helper_tpwcs.py, tweakwcs/tests/test_linalg.py, tweakwcs/tests/test_wcsutils.py, tweakwcs/tpwcs.py, tweakwcs/wcsimage.py, tweakwcs/wcsutils.py
Use same data type aliases consistently throughout the code.
=> Use numpy data types in a consistent way

tweakwcs/imalign.py, tweakwcs/linearfit.py, tweakwcs/tests/test_imalign.py
=> Use numpy data types in a consistent way. Part II

azure-templates.yml
See https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/
=> Modify Mac OS version for Azure pipeline

CHANGELOG.rst
Update changelog with the release date.
=> Release 0.7.0

CHANGELOG.rst, tweakwcs/matchutils.py, tweakwcs/tests/test_matchutils.py
=> Peak coordinates must be inside the image

setup.py, tweakwcs/linearfit.py, tweakwcs/tests/test_linearfit.py
A simple alternative to #137. Test example was copied/adapted from #137.
There is no changelog entry for something that is temporarily here [until/unless we decide it is permanently here].
=> Add support for 2D vector-model fitting

CHANGELOG.rst
Prepare changelog for release `0.7.2` and also add a changelog entry for https://github.com/spacetelescope/tweakwcs/pull/138.
=> Release version 0.7.2

.readthedocs.yml
This replaces the legacy build specification.
=> Update RTD config to use new build specification

setup.py
Continue unfinished changes from https://github.com/spacetelescope/tweakwcs/pull/175
=> Remove codecov II

azure-pipelines.yml, azure-templates.yml
=> Update Azure pipelines

tweakwcs/correctors.py, tweakwcs/imalign.py, tweakwcs/wcsimage.py
=> Update docs to include more info about tangent plane units

azure-pipelines.yml
Potential fix for build error in #189
=> Use build package to generate source distribution archive

CHANGELOG.rst, tweakwcs/imalign.py
=> Fix a bug in align_wcs that disables expand_refcat

README.rst
Resolves [SCSB-133](https://jira.stsci.edu/browse/SCSB-133)
=> [SCSB-133] rename references to master branch

pyproject.toml, tweakwcs/tests/test_correctors.py, tweakwcs/tests/test_jwst_utils.py
Fixes unit tests failures with gwcs>=0.24
cc: @jhunkeler
=> Fix failing unit tests with gwcs>=0.24

.github/workflows/ci.yml, tox.ini
=> Update CI to test with Python 3.13

CHANGELOG.rst
Regression tests:
JWST: https://github.com/spacetelescope/RegressionTests/actions/runs/14177042557
Roman: https://github.com/spacetelescope/RegressionTests/actions/runs/14177051819
=> Update changelog for the upcoming release

CHANGELOG.rst, tweakwcs/wcsimage.py
Fix a bug in a log message in XYXYMatch.
Closes #227
=> Fix a bug in a log message in XYXYMatch
