tweakwcs/imalign.py
tweakwcs/wcsimage.py

This PR removes debugging prints left over from when I was trying to understand why the code did not work. It turns out it was a bug in `jwst_pipeline` already fixed.

Remove debugging prints

---

tweakwcs/matchutils.py
tweakwcs/tpwcs.py

This PR makes it easier to initialize a JWST-specific WCS object using `meta.wcsinfo` instead of explicitly passing each angle to the initializer.
CC: @larrybradley @hcferguson 
If you are trying to run examples from PRs #1 or #2, then you will need to replace the following step:
```python
wcsinfo = im1.meta.wcsinfo._instance
imwcs = JWSTgWCS(
wcs=deepcopy(im1.meta.wcs),
v2_ref=wcsinfo['v2_ref'] / 3600.0,
v3_ref=wcsinfo['v3_ref'] / 3600.0,
roll_ref=wcsinfo['roll_ref'],
ra_ref=wcsinfo['ra_ref'],
dec_ref=wcsinfo['dec_ref']
)
```
with the following simple statement:
```python
imwcs = JWSTgWCS(wcs=deepcopy(im1.meta.wcs), im1.meta.wcsinfo._instance)
```

Initialize JWSTgWCS using wcsinfo instead of individual ref angles

---

tweakwcs/imalign.py
tweakwcs/wcsimage.py

This PR adds another function, `tweak_image_wcs()` that not only allows adjusting the WCS of multiple images at once (equivalent to calling `tweak_wcs()` in a loop for each input catalog) but also incorporates several operations on input image objects (such as calling `match()`, updating image object's `wcs`, etc.).
The most important difference, however, is that due to the fact that this function takes multiple images (as opposite to two catalogs accepted by `tweak_wcs()`), this function can optimize the order in which image alignment should occur and also expand the reference catalog with new sources from already aligned images. This allows alignment of images that do not all overlap but overlap only in pairs.
CC: @larrybradley @hcferguson

Add a function that tweaks multiple nddata images at once

---

docs/index.rst
docs/tweakwcs/groupwcs.rst
tweakwcs/groupwcs.py

This adds SCA auto-grouping utility function for `JWST` data.
CC: @larrybradley @hcferguson

Add SCA auto-grouping for JWST data

---

tweakwcs/tpwcs.py

This PR ports the changes from the JWST pipeline to `tweakwcs` related to the use of frames instead of string frame names. For more details see https://github.com/spacetelescope/jwst/pull/2404, https://github.com/spacetelescope/jwst/pull/2590, and https://github.com/spacetelescope/jwst/pull/2629.

Use WCS frames instead of frame names

---

tweakwcs/wcsimage.py

This is an obvious typo that needs to be fixed and affects computation of a the convex hull when only 2 or 3 sources are present.

Fix a type in branching by number of points

---

tweakwcs/linearfit.py
tweakwcs/tpwcs.py

This PR adds support for aligning FITS WCS.
Example usage:
```python
misaligned_wcs = HSTWCS('j8bt06nyq_flt.fits', ext=1)
imwcs = FITSWCS(wcs= misaligned_wcs)
aligned_wcs = imwcs.wcs
```
CC: @stscicrawford @stsci-hack

Add support for aligning FITS WCS

---

notebooks/align_fits_wcs.ipynb

Add a second example of aligning FITS WCS using lower-level functions. The same workflow can be used for aligning images to an external reference catalog.
CC: @stsci-hack

Add customizable FITS WCS alignment to reference catalogs

---

docs/index.rst
docs/tweakwcs/wcsimage.rst
tweakwcs/imalign.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py

`tweak_image_wcs` now will add `'tweakwcs_info'` key to the meta attribute of input `NDData` objects which will point to a dictionary of various fit and match info.
`tweak_wcs` will directly set these fit info on `TPWCS.meta`.
For example,
```python
tweak_image_wcs([im1, im2])
twinfo1 = im1.meta.info('tweakwcs_info', None)
if twinfo1 is None:
print("image 1 was used as a reference image and was not aligned")
else:
print(twinfo1)  # for standard NDData
```
CC: @stsci-hack @shannnnnyyy

Return fit and match info in TPWCS and NDData meta

---

tweakwcs/imalign.py
tweakwcs/tpwcs.py

This PR addresses the issue described in https://github.com/spacetelescope/tweakwcs/pull/22 and adds safeguards to detect when a reference catalog has an unsupported type. (and a small doc fix).
The fix in this PR will work when reference catalog is of `astropy.nddata.NDData` type unlike the fix proposed in https://github.com/spacetelescope/tweakwcs/pull/22.
CC: @stsci-hack

Fix undefined variable when refcat is provided

---

tweakwcs/imalign.py
tweakwcs/linearfit.py
tweakwcs/wcsimage.py

This PR adds a new `'status'` keyword that is being added to the `tweakwcs_info` value in images' meta attribute. This allows to check the status of alignment: 'SUCCESS', 'REFERENCE' (to indicate that an image was not aligned because it was *chosen* to be a reference image), or 'FAILED'.
Other improvements:
* Added `'eff_nclip'` to the `fit` results dictionary. May be added later to the `tweakwcs_info` in image's meta at a later time if this kind of detail is necessary.
* Improved documentation
* More robust detection of JWST `DataModel` and correct extraction of the `gWCS` WCS from it.
* Now `image.meta['tweakwcs_info']` is always present in images' `meta` upon return from `tweak_image_wcs()`. No need to check for its presence.

Add alignment status to tweakwcs_info meta

---

CHANGELOG.rst
tweakwcs/wcsimage.py

This PR fixes the code to update ``'fit_ref_idx'`` and ``'fit_input_idx'`` fields in the reported fit results. These fields are the indices of the matched sources after some of them are clipped away during the _fitting_ process (_after matching_). Therefore the length of these indices is (usually) smaller than that of the _matched_ indices.
**NOTE:** Due to the bug in `xyxymatch` described in https://github.com/spacetelescope/stsci.stimage/issues/8, matched indices (and possibly "fit" indices) may contain duplicates.

Update reported indices in `fit` after clipping iterations

---

src/carrutils.c

The fix in https://github.com/spacetelescope/tweakwcs/pull/34 fills the newly allocated arrays before checking the returned pointer thus making the check pointless and the code less reliable.
Pointer check should be moved before array fill operation.

Array should be filled after pointer validity check, not before

---

pyproject.toml
setup.py

Latest `setuptools` produces the following error during build:
```        
from setuptools import setup, find_packages, Extension, _install_setup_requires
ImportError: cannot import name '_install_setup_requires'
```
This implements `pyproject.toml` (PEP517) as a replacement.

Fix setuptools

---

src/carrutils.c

Seen here: https://dev.azure.com/spacetelescope/drizzlepac/_build/results?buildId=22&view=logs&jobId=bfe8a88d-3928-550a-8c7c-c7cdeca2abfc&taskId=41b9b801-0fbe-5309-8a48-81b7a46eae1f&lineStart=173&lineEnd=183&colStart=1&colEnd=1
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DNUMPY=1 -D_CRT_SECURE_NO_WARNING -D__STDC__=1 -IC:\Users\VSSADM~1\AppData\Local\Temp\pip-build-env-8tibd8q1\overlay\Lib\site-packages\numpy\core\include -IC:\hostedtoolcache\windows\Python\3.7.2\x64\include -IC:\hostedtoolcache\windows\Python\3.7.2\x64\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual …
```

[WIP] Fix void unknown size

---

azure-templates.yml
setup.py

(`CODECOV_TOKEN` is defined at the project level -- similar to how we do this in Jenkins)

Azure: Add codecov

---

azure-templates.yml

Makes it easier to cherry-pick the environment from a build log

Azure: Show pip freeze output

---

tweakwcs/tests/helper_tpwcs.py
tweakwcs/tests/test_tpwcs.py

Instead of indexing `model.Parameter` index the value of the parameter.
This removes ambiguity in the current code where indexing is of a `Parameter` instance returns one parameter in a model set. With this changes the code works with current astropy.modeling master and the future refactored modeling.
In addition the `prepare_inputs/outputs` calls were removed as they are not necessary in this case.

change indexing in model parameters

---

azure-templates.yml

This allows pipeline related tests to execute.
~Note: `stable` branch may be significantly behind `master`.~ Cannot use `stable` branch at this time. The previous release of `jwst` was incompatible with MSVC.

Azure: Require jwst package (master)

---

CHANGELOG.rst
tweakwcs/matchutils.py
tweakwcs/wcsimage.py

This PR fixes logging deprecation warnings and adds logic to compute image group's **catalog**
name using a common prefix (if exists) of the names of constituent images/catalogs.

Fix logging and add group name deduction logic

---

CHANGELOG.rst
tweakwcs/imalign.py
tweakwcs/tests/test_imalign.py
tweakwcs/wcsimage.py

Original code was too restrictive: it _required_ all input images to have non-empty source catalogs. This PR relaxes this requirement and allows alignment to proceed as long as there are enough images with non-empty catalogs.
This PR fixes https://github.com/spacetelescope/jwst/issues/4261

Allow some empty input catalogs

---

CHANGELOG.rst
tweakwcs/tests/helper_tpwcs.py
tweakwcs/tests/test_jwst_utils.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tests/test_wcsutils.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py
tweakwcs/wcsutils.py

This PR replaces `TPCorr` model (from the `jwst` pipeline) with standard models from `astropy` and `gwcs`. Therefore, `jwst` package is no longer needed to be able to align JWST images (kind of... `DataModel` is still needed...)

Replace TPCorr with standard astropy/gwcs models in the JWST WCS corrector

---

CHANGELOG.rst
tweakwcs/tpwcs.py

This PR temporarily disables circular definition of inverses of the tangent-plane correction models due to issues in #97. This should be re-enabled once https://github.com/spacetelescope/asdf/issues/744 and https://github.com/spacetelescope/asdf/issues/745 are taken care of.
This PR also corrects the angle wrap value used in cartesian<->spherical models.
This PR cannot be merged until https://github.com/spacetelescope/gwcs/pull/284 is merged

Temp disable inv of inv and fix angle wrapping

---

tweakwcs/tests/helper_tpwcs.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tests/test_wcsutils.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py

This PR removes wrapping of `lon` angle at 360 in the temporary code used for JWST WCS _in case when_ latest `gwcs`(i.e., master) is not available.

Wrap lon to pm 180 range in temp code

---

CHANGELOG.rst
tweakwcs/linearfit.py
tweakwcs/tests/test_imalign.py
tweakwcs/tests/test_linearfit.py
tweakwcs/tests/test_wcsimage.py
tweakwcs/wcsimage.py

This PR deals with the following issues:
1. In the previous versions, the linear fit functions returned the transposed transformation matrix instead of directly returning the matrix itself. This PR modifies this behavior and now the linear fit functions will return the rotation/scale matrix un-transposed.
2. Increased the use of `longdouble` for internal computations for (hopefully) improved accuracy.
3. Improved documentation for `tweakwcs.linearfit.build_fit_matrix` and documentation formatting  for `tweakwcs.linearfit` module.

Linear fit functions should return un-transposed matrix

---

tweakwcs/imalign.py
tweakwcs/linalg.py
tweakwcs/matchutils.py
tweakwcs/tpwcs.py
tweakwcs/utils/jwst_utils.py
tweakwcs/wcsimage.py

Fix issues with formatting of parameters and types in the documentation.

Fix parameter name and type formatting in docs

---

CHANGELOG.rst
tweakwcs/imalign.py
tweakwcs/linearfit.py
tweakwcs/tests/test_imalign.py
tweakwcs/tests/test_linearfit.py
tweakwcs/wcsimage.py

This PR re-organizes how results of the fits are being reported. In my opinion now the structure of the `fits_info` dictionary is a little bit more clear.
``rot`` now   becomes ``proper_rot`` and ``rotxy`` now becomes ``rot`` containing only  ``rotx`` and ``roty``. Also, ``scale`` now is a tuple of only two scales ``sx`` and ``sy``. The geometric mean scale is now a separate field ``'<scale>'`` as well as the arithmetic mean of rotation angles (``'<rot>'``). Finally, ``'offset'`` in the fit functions from the ``linearfit`` module was renamed to ``'shift'`` in order to match the same field returned by functions from the ``imalign`` module.
This change is backward incompatible but the only user(s) who might be affected, to the best of my knowledge, are @stsci-hack and @mdlpstsci.

Rename and re-organize fields in the fit_info dictionary

---

CHANGELOG.rst
tweakwcs/tests/test_imalign.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py

This PR fixes a bug in the alignment of multi-chip FITS WCS images resulting in relative mis-alignment of chips. Only the first chip was aligned correctly. The issue was reported by @stsci-hack 
The root-cause of the issue appears to be due to the code being originally designed to work with JWST's `gwcs` which required special transformation of transformations computed in the reference tangent plane to image's tangent plane. When FITS code was ported from `tweakreg` I missed that _that_ code was already doing this transformation and so it was applied twice.

Fix a bug in alignment of multi-chip FITS images

---

setup.py
tweakwcs/tests/helper_tpwcs.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tests/test_wcsutils.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py

This PR allows the use of the FITS WCS corrector with `astropy` versions >= 3.1 but less than 4.0 that is required for supporting JWST's WCS. `gwcs` package now is optional and required only if support for JWST's WCS is needed.

Make support for JWST WCS optional

---

CHANGELOG.rst
tweakwcs/tpwcs.py

Detect `PC`-based non-HST WCS and correct `PC` matrix instead of the `CD` matrix.

Support non-HST PC-based WCS

---

CHANGELOG.rst
tweakwcs/linearfit.py

Currently reported rotation angles are in the range `[0, 360]`. However, since these are "corrections" being applied, they typically should be small angles centered on 0. Therefore it makes more sense to report rotation angles in the range `[-180, 180]` degrees. This PR changes the value at which reported rotation angles are wrapped to 180.

Change the angle at which rotation angles are wrapped

---

CHANGELOG.rst
tweakwcs/tpwcs.py

Current code does not handle well WCS objects created with `stwcs.wcsutil.HSTWCS` due to how  `HSTWCS.all_world2pix()` does not handle scalar input arguments (unlike `astropy.wcs.WCS`). Special handling is required to deal with `HSTWCS`.

Fix a possible crash when aligning FITS WCS

---

CHANGELOG.rst
tweakwcs/tests/test_tpwcs.py
tweakwcs/tpwcs.py

This PR fixes a bug due to which the inverse of the compound model was not updated when the forward model was updated.
In addition, tolerances on JWST tests have been tightened back to their original levels except for the `test_tpwcs.test_jwstgwcs_tangent_to_world()` which is still 1000 times less accurate than the old `TPCorr`-based test. I will be investigating this in the future.
Finally, this test adds a regression-like test for aligning multi-chip JWST images (i.e., single-chip images that belong to the same "group") that replicates the corresponding `FITS` test and shows that JWST algorithm can align ideal images/catalogs (using same data as the `FITS` test) to almost the same accuracy as FITS corrector: to 3e-9 in RA and 1e-10 in DEC (RMS).

Update the inverse of JWST model when updating forward model

---

tweakwcs/tests/test_multichip_jwst.py

Finally, this test adds a regression-like test for aligning multi-chip JWST images (i.e., single-chip images that belong to the same "group") that replicates the corresponding FITS test and shows that JWST algorithm can align ideal images/catalogs (using same data as the FITS test) to almost the same accuracy as FITS corrector: to 3e-9 in RA and 1e-10 in DEC (RMS).
This test was supposed to go into #112

Add multi-chip test for the JWST WCS corrector

---

CHANGELOG.rst
tweakwcs/tpwcs.py

Compute tangent plane-to-tangent plane projection for JWST transformations at the center of the given pixel instead at its border. The is no expected effect from this change or it should be practically undetectable.

Compute TP to TP projection at the center of the pixel

---

CHANGELOG.rst
tweakwcs/tpwcs.py

Using `tweakwcs` version `0.6.1` in the `jwst` pipeline results in crash for MIRI images due to a scale of a linear transformation being evaluated at a location outside the bounding box of the WCS being aligned. This resulted in matrices filled with `nan`s.
CC: @jdavies-st @nden

Estimate scale of affine transform within bounding box limits

---

CHANGELOG.rst
tweakwcs/tpwcs.py

Fixes a crash when `tweawcs` is run twice on the same set of images but one of the input images in the second run was used as a "regular" input image in the second run. The same error could also happen if in a previous run some of the images failed to be aligned.

Detect when fit_info does not contain center

---

CHANGELOG.rst
tweakwcs/linalg.py
tweakwcs/tpwcs.py

The bug fixed in this PR resulted in incorrect application of subsequent corrections to a JWST WCS that already contained a tangent plane correction transformations resulting in misaligment of individual images in a previously aligned group of images.
Fixes https://github.com/spacetelescope/jwst/issues/4918

Fix how multiple corrections are applied to JWST WCS

---

tweakwcs/tpwcs.py

Compute center (used only for scale computation) only when needed - when scale is not provided.

Compute center only when needed

---

CHANGELOG.rst
tweakwcs/tpwcs.py

The code for creating a `JWSTgWCS` corrector class from a previously corrected `gWCS` object crashes. The initialization fails due to the code being unable to extract _some_ submodels of a coumpound model.
This PR provides a temporary (or a permanent) solution until the issue is being investigated.

Bug fix: Unable to initialize JWSTgWCS from corrected WCS

---

CHANGELOG.rst
azure-templates.yml
tweakwcs/imalign.py
tweakwcs/tests/test_imalign.py
tweakwcs/tests/test_multichip_fitswcs.py
tweakwcs/wcsimage.py

This PR adds `ref_tpwcs` parameter to `imalign.fit_wcs()`, `imalign.align_wcs()`, `wcsimage.WCSGroupCatalog.align_to_ref()` to allow alignment to be performed in a user-specified distortion-free tangent plane.

Allow users to specify alignment tangent plane

---

CHANGELOG.rst
tweakwcs/imalign.py
tweakwcs/linearfit.py
tweakwcs/tests/coveragerc
tweakwcs/tests/test_imalign.py
tweakwcs/tests/test_linearfit.py
tweakwcs/wcsimage.py

This PR adds a new `'rshift'` fitting mode to the existing list of `fitgeom` modes. This will allow fitting only for shifts and rotations without fitting for scale.
CC: @stsci-hack

Add rshift fitting mode

---

CHANGELOG.rst
tweakwcs/tests/helper_tpwcs.py
tweakwcs/tests/test_matchutils.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tpwcs.py

This PR adds support for JWST VA-corrected `v2v3` WCS frames called `v2v3vacorr`. When present, WCS "tweaking" will be performed on VA-corrected frame and when it is not present in the WCS's pipeline, the original `v2v3` frame will be used.
A new release of `tweakwcs` is necessary before https://github.com/spacetelescope/jwst/pull/5602 can be merged.

Add support for JWST VA corrected V2V3 frames

---

azure-pipelines.yml
azure-templates.yml
tweakwcs/linalg.py
tweakwcs/linearfit.py
tweakwcs/tests/test_linearfit.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tests/test_wcsimage.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py

Fix deprecation warnings due to `numpy` types and `gwcs`'s pipeline access issues.
Fixes #127

Fix deprecation warnings

---

setup.py
tweakwcs/imalign.py
tweakwcs/tests/test_wcsimage.py
tweakwcs/wcsimage.py

This PR will attempt to catch `spherical_geometry` exceptions and fall back to some less accurate but (hopefully) acceptable alternative handling.
Fixes #134 and many other similar issues in the `JWST` pipeline (hopefully):
Fixes https://github.com/spacetelescope/jwst/issues/4601
Fixes https://github.com/spacetelescope/jwst/issues/3764

Make code more robust to exceptions in the spherical geometry

---

CHANGELOG.rst
tweakwcs/imalign.py
tweakwcs/tests/test_imalign.py
tweakwcs/wcsimage.py

As reported in https://github.com/spacetelescope/tweakwcs/pull/141 user-provided `minobj` parameter is ignored in calls to ``WCSGroupCatalog.align_to_ref()`` and ``align_wcs()``. This PR replaces #141 by implementing almost identical fix as proposed in #141 plus a changelog entry and a unit test. Also, the debug logging message is issued only when user does not provide a `minobj` value.
Closes #141

Do not ignore user-provided minobj parameter

---

setup.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py

`distutils.LooseVersion` is deprecated. The recommended way to check the version now is using `packaging`.

Replace deprecated code

---

azure-templates.yml

Add Python 3.9 and 3.10 to CI testing matrix.

Add Python 3.9 and 3.10 to CI testing matrix

---

docs/source/conf.py
tweakwcs/tests/helper_tpwcs.py
tweakwcs/tests/test_multichip_jwst.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tests/test_wcsutils.py

This PR uses `packaging.version` instead of `distutils`' `LooseVersion` to avoid numerous deprecation warnings.

Fix deprecation warnings for using disutils LooseVersion

---

tweakwcs/linearfit.py

This is to deal with upcoming deprecation of `_fitter_to_model_params` in `astropy 5.1`.

Fix deprecation warning for upcoming astropy release

---

tweakwcs/tests/test_tpwcs.py
tweakwcs/tpwcs.py

Quiet deprecation warnings from `gwcs`:
```python
wcs.py:2947: DeprecationWarning: Indexing a WCS.pipeline step is deprecated. Use the `frame` and `transform` attributes instead.
```

Fix deprecation warnings when indexing gwcs pipeline steps

---

tweakwcs/tests/test_multichip_jwst.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tests/test_wcsutils.py
tweakwcs/tpwcs.py

Since https://github.com/spacetelescope/tweakwcs/pull/153 these checks for `astropy` version `> 4.0` are not necessary.

Remove tests for astropy versions GT 4.0

---

setup.py
tweakwcs/tests/helper_tpwcs.py
tweakwcs/tests/test_multichip_jwst.py
tweakwcs/tests/test_tpwcs.py
tweakwcs/tests/test_wcsutils.py
tweakwcs/tpwcs.py
tweakwcs/wcsimage.py

In https://github.com/spacetelescope/tweakwcs/pull/155 switched to accessing `gwcs` pipeline via `Step` properties instead of pipeline indexing. This requires `gwcs>=0.14`. Requiring this in `setup.py` essentially makes unnecessary all the version checks for the `gwcs` package that are in the current code.
This PR increases `gwcs` version requirement and removes version checks.

Set minimum gwcs version to 0.14

---

CHANGELOG.rst
tweakwcs/imalign.py
tweakwcs/linearfit.py
tweakwcs/wcsimage.py

Closes #168 
This PR exposes ``clip_accum`` parameter that fine-tunes model fitting process to higher-level functions.

Expose clip_accum parameter in top-level functions

---

CHANGELOG.rst
tweakwcs/correctors.py
tweakwcs/matchutils.py
tweakwcs/tests/test_matchutils.py
tweakwcs/tests/test_multichip_fitswcs.py
tweakwcs/tests/test_multichip_jwst.py
tweakwcs/tests/test_wcsimage.py
tweakwcs/wcsimage.py

The bins of the 2D histogram used to find initial shifts for matching of JWST catalogs are too large compared to pixel size due to the fact that bins were in the tangent plane units and did not take into account pixel scale.

Fix bin size in 2D histogram used in matching

---

azure-templates.yml
setup.py

the `codecov` package is now deprecated and has been yanked from PyPI

remove usages of deprecated `codecov` package

---

CHANGELOG.rst
tweakwcs/imalign.py
tweakwcs/tests/test_wcsimage.py
tweakwcs/wcsimage.py

This PR adds an argument (`group_bb_policy` and `bb_policy`) that controls how the bounding box is computed for groups of images. It introduces a new algorithm that approximates the bounding box using convex hull of individual images' bounding polygons instead of computing the exact union of individual polygons. The exact algorithm becomes extremely slow for large groups of images (>50).

Allow approximate computation of bounding polygons for large groups

---

CHANGELOG.rst
LICENSE.txt
docs/rtd-pip-requirements.txt
tweakwcs/correctors.py
tweakwcs/linalg.py
tweakwcs/tests/test_linearfit.py

This PR fixes the bug reported in https://github.com/spacetelescope/tweakwcs/pull/184 and also fixes incompatibility with future numpy 2.0 (this is the fix as proposed in #182).
Also fixed RTD build as in https://github.com/spacetelescope/jwst/pull/7787
Closes #184

Fix a bug preventing usage of numpy.linalg.inv and fix numpy 2.0 compatibility

---

README.rst

Looks like you have a DOI via release webhook. You should advertise it. cc @rosteen 
p.s. Are you still using Azure Pipelines? Why not Actions?

Add Zenodo badge

---

CHANGELOG.rst
tweakwcs/imalign.py

This PR addresses the issue `JP-3468` (excerpt):
> When running the TweakRegStep with expand_refcat=True, if aligning an image fails, its sources are still added to the reference catalog.  This breaks the astrometric consistency of the reference catalog, and the next image(s) can lock onto these unaligned sources (or just not match and add even more unaligned sources).  This can cause a cascade of misaligned images that can report the alignment as successful. 
Reported by @Vb2341

Improve how reference catalog is expanded

---

CHANGELOG.rst
tweakwcs/matchutils.py

_xy_2dhist currently computes the differences in positions between all n * m pairs of stars in the image and reference catalogs.  This can be a lot as images become large.  Only pairs in a box of size 2 * r actually end up contributing to the histogram, so most of these differences end up being discarded.
Adding a kdtree to prefilter the matches to only those in a circle of radius sqrt(2) * r means that most of these matches don't need to be computed.  This PR adds that prefiltering.
I have only verified that tests pass and that the particular case I was trying to run in Roman now succeeds.  I'm happy to run more tests as appropriate.

Use KDTree to reduce memory & compute in _xy_2dhist

---

.github/workflows/ci.yml
pyproject.toml

resolves [SCSB-145](https://jira.stsci.edu/browse/SCSB-145)
propagate Astropy's deprecation of Python 3.9 to downstream packages
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:

[SCSB-145] require Python 3.10

---

CHANGELOG.rst
tweakwcs/imalign.py
tweakwcs/tests/test_imalign.py

align_wcs to raise custom exception when not enough inputs

---

CHANGELOG.rst
tweakwcs/matchutils.py
tweakwcs/tests/test_matchutils.py

This PR catches the `RuntimeError` raised by `xyxymatch` when multiple reference sources match a single source and raises a custom exception.
This change is motivated by the error handling code in jwst and romancal which inspect the error message and can be simplified once the changes in this PR are released.
See the below linked issue for details and why this change is being made in tweakwcs instead of `xyxymatch`
Closes https://github.com/spacetelescope/stsci.stimage/issues/33

catch RuntimeError and raise custom exception for xyxymatch error

---

.github/workflows/ci.yml
tox.ini
tweakwcs/linearfit.py
tweakwcs/tests/test_linearfit.py

Updates the test matrix and also fixes an incompatibility with upcoming changes in `astropy 7.0` - see https://github.com/astropy/astropy/pull/16673#issuecomment-2339334721

Update test matrix

---

.github/workflows/build.yml
.github/workflows/ci.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed

---

tweakwcs/wcsimage.py

Fixes incorrect message of the exception raised when not enough sources are matched. Reported by a user.

Correct exception message when too few objects are matched
